name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install npm dependencies
      run: npm install

    - name: Stop existing PM2 process
      run: pm2 delete terry-davis-discord-bot || true

    - name: Start application with PM2
      run: pm2 start npm --name "terry-davis-discord-bot" -- run start

